/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juhoonlee
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        calText = new javax.swing.JTextField();
        calHex = new javax.swing.JRadioButton();
        calDec = new javax.swing.JRadioButton();
        calOct = new javax.swing.JRadioButton();
        calBin = new javax.swing.JRadioButton();
        calDeg = new javax.swing.JRadioButton();
        calRad = new javax.swing.JRadioButton();
        calGra = new javax.swing.JRadioButton();
        calHyp = new javax.swing.JCheckBox();
        calInv = new javax.swing.JCheckBox();
        calBack = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cal7 = new javax.swing.JButton();
        cal8 = new javax.swing.JButton();
        cal9 = new javax.swing.JButton();
        cal4 = new javax.swing.JButton();
        cal5 = new javax.swing.JButton();
        cal6 = new javax.swing.JButton();
        cal1 = new javax.swing.JButton();
        cal2 = new javax.swing.JButton();
        cal3 = new javax.swing.JButton();
        cal0 = new javax.swing.JButton();
        calDot = new javax.swing.JButton();
        calDiv = new javax.swing.JButton();
        calMul = new javax.swing.JButton();
        calMin = new javax.swing.JButton();
        calAdd = new javax.swing.JButton();
        calMod = new javax.swing.JButton();
        calOr = new javax.swing.JButton();
        calLsh = new javax.swing.JButton();
        calRes = new javax.swing.JButton();
        calAnd = new javax.swing.JButton();
        calXor = new javax.swing.JButton();
        calNot = new javax.swing.JButton();
        calRsh = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(calHex);
        calHex.setText("Hex");

        buttonGroup1.add(calDec);
        calDec.setText("Dec");

        buttonGroup1.add(calOct);
        calOct.setText("Oct");

        buttonGroup1.add(calBin);
        calBin.setText("Bin");

        calDeg.setText("Degrees");

        calRad.setText("Radians");

        calGra.setText("Grads");

        calHyp.setText("Hyp");

        calInv.setText("Inv");

        calBack.setText("Backspace");
        calBack.setPreferredSize(new java.awt.Dimension(100, 23));
        calBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calBackActionPerformed(evt);
            }
        });

        jButton3.setText("C");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cal7.setText("7");
        cal7.setSize(new java.awt.Dimension(50, 23));
        cal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal7ActionPerformed(evt);
            }
        });

        cal8.setText("8");
        cal8.setSize(new java.awt.Dimension(50, 23));
        cal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal8ActionPerformed(evt);
            }
        });

        cal9.setText("9");
        cal9.setSize(new java.awt.Dimension(50, 23));
        cal9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal9ActionPerformed(evt);
            }
        });

        cal4.setText("4");
        cal4.setSize(new java.awt.Dimension(50, 23));
        cal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal4ActionPerformed(evt);
            }
        });

        cal5.setText("5");
        cal5.setSize(new java.awt.Dimension(50, 23));
        cal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal5ActionPerformed(evt);
            }
        });

        cal6.setText("6");
        cal6.setSize(new java.awt.Dimension(50, 23));
        cal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal6ActionPerformed(evt);
            }
        });

        cal1.setText("1");
        cal1.setSize(new java.awt.Dimension(50, 23));
        cal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal1ActionPerformed(evt);
            }
        });

        cal2.setText("2");
        cal2.setSize(new java.awt.Dimension(50, 23));
        cal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal2ActionPerformed(evt);
            }
        });

        cal3.setText("3");
        cal3.setSize(new java.awt.Dimension(50, 23));
        cal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal3ActionPerformed(evt);
            }
        });

        cal0.setText("0");
        cal0.setSize(new java.awt.Dimension(50, 23));
        cal0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal0ActionPerformed(evt);
            }
        });

        calDot.setText(".");
        calDot.setSize(new java.awt.Dimension(50, 23));
        calDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calDotActionPerformed(evt);
            }
        });

        calDiv.setText("/");
        calDiv.setSize(new java.awt.Dimension(50, 23));
        calDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calDivActionPerformed(evt);
            }
        });

        calMul.setText("*");
        calMul.setSize(new java.awt.Dimension(50, 23));
        calMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calMulActionPerformed(evt);
            }
        });

        calMin.setText("-");
        calMin.setSize(new java.awt.Dimension(50, 23));
        calMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calMinActionPerformed(evt);
            }
        });

        calAdd.setText("+");
        calAdd.setSize(new java.awt.Dimension(50, 23));
        calAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calAddActionPerformed(evt);
            }
        });

        calMod.setText("Mod");
        calMod.setSize(new java.awt.Dimension(50, 23));
        calMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calModActionPerformed(evt);
            }
        });

        calOr.setText("Or");
        calOr.setSize(new java.awt.Dimension(50, 23));
        calOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calOrActionPerformed(evt);
            }
        });

        calLsh.setText("Lsh");
        calLsh.setSize(new java.awt.Dimension(50, 23));
        calLsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calLshActionPerformed(evt);
            }
        });

        calRes.setText("=");
        calRes.setSize(new java.awt.Dimension(50, 23));
        calRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calResActionPerformed(evt);
            }
        });

        calAnd.setText("And");
        calAnd.setSize(new java.awt.Dimension(50, 23));
        calAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calAndActionPerformed(evt);
            }
        });

        calXor.setText("Xor");
        calXor.setSize(new java.awt.Dimension(50, 23));
        calXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calXorActionPerformed(evt);
            }
        });

        calNot.setText("Not");
        calNot.setSize(new java.awt.Dimension(50, 23));
        calNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calNotActionPerformed(evt);
            }
        });

        calRsh.setText("Rsh");
        calRsh.setSize(new java.awt.Dimension(50, 23));
        calRsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calRshActionPerformed(evt);
            }
        });

        jButton28.setText("F-E");
        jButton28.setSize(new java.awt.Dimension(50, 23));

        jButton29.setText("(");
        jButton29.setBounds(new java.awt.Rectangle(0, 0, 60, 23));

        jButton30.setText(")");
        jButton30.setSize(new java.awt.Dimension(50, 23));

        jButton31.setText("MC");
        jButton31.setSize(new java.awt.Dimension(50, 23));

        jButton32.setText("dms");
        jButton32.setSize(new java.awt.Dimension(50, 23));

        jButton33.setText("Exp");
        jButton33.setSize(new java.awt.Dimension(50, 23));

        jButton34.setText("In");
        jButton34.setSize(new java.awt.Dimension(50, 23));

        jButton35.setText("MR");
        jButton35.setSize(new java.awt.Dimension(50, 23));

        jButton36.setText("sin");
        jButton36.setSize(new java.awt.Dimension(50, 23));

        jButton37.setText("x^y");
        jButton37.setSize(new java.awt.Dimension(50, 23));

        jButton38.setText("n!");
        jButton38.setSize(new java.awt.Dimension(50, 23));

        jButton39.setText("MS");
        jButton39.setSize(new java.awt.Dimension(50, 23));

        jButton40.setText("cos");
        jButton40.setSize(new java.awt.Dimension(50, 23));

        jButton41.setText("x^2");
        jButton41.setSize(new java.awt.Dimension(50, 23));

        jButton42.setText("1/x");
        jButton42.setSize(new java.awt.Dimension(50, 23));

        jButton43.setText("M+");
        jButton43.setSize(new java.awt.Dimension(50, 23));

        jButton44.setText("tan");
        jButton44.setSize(new java.awt.Dimension(50, 23));

        jButton45.setText("x^2");
        jButton45.setSize(new java.awt.Dimension(50, 23));

        jButton46.setText("1/x");
        jButton46.setSize(new java.awt.Dimension(50, 23));

        jButton48.setText("pi");
        jButton48.setSize(new java.awt.Dimension(50, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calHex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calDec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calOct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calBin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calInv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calHyp))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calDeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calRad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calGra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cal3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calLsh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calXor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cal0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calRes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calNot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(calBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cal7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cal8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cal9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(calDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(calMod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cal4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cal5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cal6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(calMul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(calRsh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calOr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(calAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(calText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calHex)
                    .addComponent(calDec)
                    .addComponent(calOct)
                    .addComponent(calBin)
                    .addComponent(calDeg)
                    .addComponent(calRad)
                    .addComponent(calGra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calInv)
                    .addComponent(calHyp)
                    .addComponent(calBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal7)
                    .addComponent(cal8)
                    .addComponent(cal9)
                    .addComponent(calDiv)
                    .addComponent(calMod)
                    .addComponent(calAnd)
                    .addComponent(jButton28)
                    .addComponent(jButton30)
                    .addComponent(jButton31)
                    .addComponent(jButton29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal4)
                    .addComponent(cal5)
                    .addComponent(cal6)
                    .addComponent(calMul)
                    .addComponent(calOr)
                    .addComponent(jButton32)
                    .addComponent(jButton33)
                    .addComponent(jButton34)
                    .addComponent(jButton35)
                    .addComponent(calRsh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal1)
                    .addComponent(cal2)
                    .addComponent(cal3)
                    .addComponent(calMin)
                    .addComponent(jButton36)
                    .addComponent(jButton37)
                    .addComponent(jButton38)
                    .addComponent(jButton39)
                    .addComponent(calXor)
                    .addComponent(calLsh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal0)
                    .addComponent(calDot)
                    .addComponent(calAdd)
                    .addComponent(calRes)
                    .addComponent(jButton40)
                    .addComponent(jButton42)
                    .addComponent(jButton43)
                    .addComponent(jButton41)
                    .addComponent(calNot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton44)
                    .addComponent(jButton45)
                    .addComponent(jButton46)
                    .addComponent(jButton48))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int result = 0;
    private void cal0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal0ActionPerformed
        calText.setText(calText.getText() + cal0.getText());
    }//GEN-LAST:event_cal0ActionPerformed

    private void cal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal1ActionPerformed
        calText.setText(calText.getText() + cal1.getText());
    }//GEN-LAST:event_cal1ActionPerformed

    private void cal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal2ActionPerformed
        calText.setText(calText.getText() + cal2.getText());
    }//GEN-LAST:event_cal2ActionPerformed

    private void cal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal3ActionPerformed
        calText.setText(calText.getText() + cal3.getText());
    }//GEN-LAST:event_cal3ActionPerformed

    private void cal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal4ActionPerformed
        calText.setText(calText.getText() + cal4.getText());
    }//GEN-LAST:event_cal4ActionPerformed

    private void cal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal5ActionPerformed
        calText.setText(calText.getText() + cal5.getText());
    }//GEN-LAST:event_cal5ActionPerformed

    private void cal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal6ActionPerformed
        calText.setText(calText.getText() + cal6.getText());
    }//GEN-LAST:event_cal6ActionPerformed

    private void cal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal7ActionPerformed
        calText.setText(calText.getText() + cal7.getText());
    }//GEN-LAST:event_cal7ActionPerformed

    private void cal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal8ActionPerformed
        calText.setText(calText.getText() + cal8.getText());
    }//GEN-LAST:event_cal8ActionPerformed

    private void cal9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal9ActionPerformed
        calText.setText(calText.getText() + cal9.getText());
    }//GEN-LAST:event_cal9ActionPerformed

    private void calAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calAddActionPerformed
        calText.setText(calText.getText() + " + ");
    }//GEN-LAST:event_calAddActionPerformed

    private void calMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calMinActionPerformed
        calText.setText(calText.getText() + " - ");
    }//GEN-LAST:event_calMinActionPerformed

    private void calMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calMulActionPerformed
        calText.setText(calText.getText() + " * ");
    }//GEN-LAST:event_calMulActionPerformed

    private void calDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calDivActionPerformed
        calText.setText(calText.getText() + " / ");
    }//GEN-LAST:event_calDivActionPerformed

    private void calResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calResActionPerformed
        String str[] = calText.getText().split(" ");
        if(str[1].equals("+")){
            result = Integer.parseInt(str[0]) + Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("-")){
            result = Integer.parseInt(str[0]) - Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("*")){
            result = Integer.parseInt(str[0]) * Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("/")){
            result = Integer.parseInt(str[0]) / Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("%")){
            result = Integer.parseInt(str[0]) % Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("<<")){
            result = Integer.parseInt(str[0]) << Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals(">>")){
            result = Integer.parseInt(str[0]) >> Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("&")){
            result = Integer.parseInt(str[0]) & Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("|")){
            result = Integer.parseInt(str[0]) | Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("^")){
            result = Integer.parseInt(str[0]) ^ Integer.parseInt(str[2]);
            calText.setText(Integer.toString(result));
        }else if(str[1].equals("~")){
            result = Integer.parseInt(str[0]);
            result = ~result;
            calText.setText(Integer.toString(result));
        }
    }//GEN-LAST:event_calResActionPerformed

    private void calDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calDotActionPerformed
        calText.setText(calText.getText() + ".");
    }//GEN-LAST:event_calDotActionPerformed

    private void calModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calModActionPerformed
        calText.setText(calText.getText() + " % ");
    }//GEN-LAST:event_calModActionPerformed

    private void calRshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calRshActionPerformed
        calText.setText(calText.getText() + " >> ");
    }//GEN-LAST:event_calRshActionPerformed

    private void calLshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calLshActionPerformed
        calText.setText(calText.getText() + " << ");
    }//GEN-LAST:event_calLshActionPerformed

    private void calAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calAndActionPerformed
        calText.setText(calText.getText() + " & ");
    }//GEN-LAST:event_calAndActionPerformed

    private void calOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calOrActionPerformed
        calText.setText(calText.getText() + " | ");
    }//GEN-LAST:event_calOrActionPerformed

    private void calXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calXorActionPerformed
        calText.setText(calText.getText() + " ^ ");
    }//GEN-LAST:event_calXorActionPerformed

    private void calNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calNotActionPerformed
        calText.setText(calText.getText() + " ~ ");
    }//GEN-LAST:event_calNotActionPerformed

    private void calBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calBackActionPerformed
        String str = calText.getText();
        str = str.substring(0, str.length()-1);
        calText.setText(str);
    }//GEN-LAST:event_calBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        calText.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cal0;
    private javax.swing.JButton cal1;
    private javax.swing.JButton cal2;
    private javax.swing.JButton cal3;
    private javax.swing.JButton cal4;
    private javax.swing.JButton cal5;
    private javax.swing.JButton cal6;
    private javax.swing.JButton cal7;
    private javax.swing.JButton cal8;
    private javax.swing.JButton cal9;
    private javax.swing.JButton calAdd;
    private javax.swing.JButton calAnd;
    private javax.swing.JButton calBack;
    private javax.swing.JRadioButton calBin;
    private javax.swing.JRadioButton calDec;
    private javax.swing.JRadioButton calDeg;
    private javax.swing.JButton calDiv;
    private javax.swing.JButton calDot;
    private javax.swing.JRadioButton calGra;
    private javax.swing.JRadioButton calHex;
    private javax.swing.JCheckBox calHyp;
    private javax.swing.JCheckBox calInv;
    private javax.swing.JButton calLsh;
    private javax.swing.JButton calMin;
    private javax.swing.JButton calMod;
    private javax.swing.JButton calMul;
    private javax.swing.JButton calNot;
    private javax.swing.JRadioButton calOct;
    private javax.swing.JButton calOr;
    private javax.swing.JRadioButton calRad;
    private javax.swing.JButton calRes;
    private javax.swing.JButton calRsh;
    private javax.swing.JTextField calText;
    private javax.swing.JButton calXor;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton48;
    // End of variables declaration//GEN-END:variables
}
